# Use uma imagem base do OpenJDK
FROM openjdk:17-jdk-alpine

# Diretório de trabalho
WORKDIR /app

# Copie o arquivo JAR gerado pelo Maven/Gradle
COPY target/RelatorioPDF-0.0.1-SNAPSHOT.jar

# Exponha a porta da aplicação
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]